import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  logoContainer: {
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 30,
  },
  logo: {
    width: 200,
    height: 200,
  },
  textContainer: {
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  titleText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000000',
    marginTop: 150,
    marginHorizontal: 40,
    textAlign: 'center',
  },
  subtitleText: {
    fontSize: 18,
    color: '#000000',
    marginTop: 10,
    marginHorizontal: 40,
    textAlign: 'center',
  },
  buttonContainer: {
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  googleButton: {
    flexDirection: 'row',
    backgroundColor: '#1E90FF',
    width: 300,
    height: 50,
    borderRadius: 10,
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: 20,
    paddingHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  googleIconContainer: {
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    borderRadius: 10,
    height: 30,
    width: 30,
  },
  googleIcon: {
    height: 20,
    width: 20,
  },
  googleText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  otherButton: {
    backgroundColor: '#F5F5F5',
    width: 300,
    height: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    paddingHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  otherText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000000',
  },
  continueText: {
    fontSize: 16,
    color: '#A9A9A9',
    marginTop: 30,
    marginHorizontal: 40,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    width: '100%',
    height: 250,
    borderRadius: 10,
    justifyContent: 'flex-start',
    alignItems: 'center',
    padding: 20,
    bottom: 0,
    position: 'absolute',
  },
  facebookButton: {
    flexDirection: 'row',
    backgroundColor: '#3b5998',
    width: 300,
    height: 50,
    borderRadius: 10,
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: 20,
    paddingHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  facebookIconContainer: {
    backgroundColor: '#3b5998',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 5,
    borderRadius: 10,
    height: 30,
    width: 30,
  },
  facebookIcon: {
    height: 25,
    width: 25,
  },
  facebookText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  rowButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: 300,
    height: 50,
    marginTop: 20,
  },
  smallButton: {
    backgroundColor: '#FFFFFF',
    width: 140,
    height: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  smallButtonText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000000',
  },
  modalTitle: {
  fontSize: 20,
  fontWeight: 'bold',
  color: '#000000',
  marginBottom: 10,
},
input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    backgroundColor: '#fff',
    marginBottom: 12,
  },
  button: {
    backgroundColor: '#D62626',
    padding: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 16,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
  footerText: {
    marginTop: 20,
    textAlign: 'center',
    color: '#555',
  },
  link: {
    fontWeight: 'bold',
    color: '#000',
  },

});
